import type { NextPage } from 'next'
import Head from 'next/head'
import { GetBossFightsToLog } from '../mocks/getBossFightsToLog'
import styled from 'styled-components'

const Main = styled.div`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`
const Container = styled.div`
  padding: 0 2rem;
`

const Home: NextPage = ({ data }: { data: object }) => {
  console.log(data)
  return (
    <Container>
      <Head>
        <title>WarcraftLogs Blamer - by tenacious || EU-Venoxis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <div>Hello there</div>
      </Main>
    </Container>
  )
}

export default Home

Home.getInitialProps = async () => {
  try {
    // const res = await axios.get(`${process.env.BACKEND_URL}`);
    // const data = res.data;
    return { ...GetBossFightsToLog }
  } catch (error) {
    return { error }
  }
}
